module RbsRails
  module ActiveRecord
    class Enum
      attr_reader ast: Parser::AST::Node?

      IGNORED_ENUM_KEYS: Array[Symbol]

      def initialize: (Parser::AST::Node? ast) -> void
      def methods: () -> Array[String]

      private

      def method_name: (Hash[untyped, untyped], String, String) -> String
      def definitions: () -> Array[Hash[untyped, untyped]]
      def traverse: (Parser::AST::Node node) { (Parser::AST::Node) -> untyped } -> untyped
                  | (Parser::AST::Node node) -> Enumerator[Parser::AST::Node, untyped]
    end
  end
end

